/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;
import negocio.Empresa;

/**
 *
 * @author USUARIO
 */
public class FormEmpresaNuevo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormEmpresaNuevo.class.getName());
    
    private Empresa myEmpresa;
    /**
     * Creates new form FormEmpresaNuevo
     */
    public FormEmpresaNuevo() {
        this.myEmpresa=new Empresa();
        initComponents();
        //setLocationRelativeTo... permita centrar el formulario
        this.setLocationRelativeTo(null);
        //setSize permite dar un tamaño (ancho,alto)
        //el metodo this.pack(); permite ajustar el tamaño segun los componentes arrastrados
        //pero para que todos queden iguales tendría que dar la orden setSize
        this.setSize(800, 600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmdGestionCamion = new javax.swing.JButton();
        cmdGestionPedidos = new javax.swing.JButton();
        cmdGestionProductos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EMPRESA DE TRANSPORTE MERCANCIA");
        setPreferredSize(new java.awt.Dimension(747, 474));

        cmdGestionCamion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmdGestionCamion.setText("GESTION CAMIONES");
        cmdGestionCamion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cmdGestionCamion.addActionListener(this::cmdGestionCamionActionPerformed);

        cmdGestionPedidos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmdGestionPedidos.setText("GESTION PEDIDOS");
        cmdGestionPedidos.setActionCommand("GESTION PRODUCTOS");
        cmdGestionPedidos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cmdGestionProductos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmdGestionProductos.setText("GESTION PRODUCTOS");
        cmdGestionProductos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(cmdGestionCamion, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addComponent(cmdGestionProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
            .addGroup(layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(cmdGestionPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdGestionCamion, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdGestionProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(cmdGestionPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdGestionCamionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGestionCamionActionPerformed
        // TODO add your handling code here:
        FormCamiones myC=new FormCamiones(this);
        myC.setVisible(true); 
    }//GEN-LAST:event_cmdGestionCamionActionPerformed

    public Empresa getMyEmpresa() {
        return myEmpresa;
    }

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormEmpresaNuevo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdGestionCamion;
    private javax.swing.JButton cmdGestionPedidos;
    private javax.swing.JButton cmdGestionProductos;
    // End of variables declaration//GEN-END:variables
}
