package presentacion;
import java.util.Date;



/**
 *ARRAYLIST
 * @author estudiantes
 */
public class FormCamiones extends javax.swing.JFrame {
    
    private FormEmpresaNuevo myPrincipal;
    
    /**
     * Creates new form ForEmpresa
     */
    public FormCamiones(FormEmpresaNuevo fp) {
        this.myPrincipal=fp;
        
        initComponents();
        //coloca el formulario en el centro de la pantalla
        this.setLocationRelativeTo(null);
        this.setSize(800,600);
        
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPLACA = new javax.swing.JTextField();
        txtCARGA = new javax.swing.JTextField();
        txtCONSUMO = new javax.swing.JTextField();
        cmdREGISTRARCAMION = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cmdCamionMenorConsumo = new javax.swing.JButton();
        cmdPromedioCarga = new javax.swing.JButton();
        cmdBuscarCargaCamion = new javax.swing.JButton();
        cmdListarCamiones = new javax.swing.JButton();
        cmdLIMPIAR = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMOSTRAR = new javax.swing.JTextArea();
        jCalendarComboBox1 = new de.wannawork.jcalendar.JCalendarComboBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FORMULARIO EMPRESA CAMION");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("REGISTRO DE DATOS CAMION"));

        jLabel1.setText("PLACA:");

        jLabel2.setText("CARGA(kg):");

        jLabel3.setText("CONSUMO(gas/km):");

        txtCONSUMO.setToolTipText("");

        cmdREGISTRARCAMION.setText("REGISTRAR CAMION");
        cmdREGISTRARCAMION.addActionListener(this::cmdREGISTRARCAMIONActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCONSUMO, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCARGA, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPLACA, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(cmdREGISTRARCAMION)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPLACA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCARGA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCONSUMO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cmdREGISTRARCAMION)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("SERVICIOS"));

        cmdCamionMenorConsumo.setText("CAMION MENOR CONSUMO");
        cmdCamionMenorConsumo.addActionListener(this::cmdCamionMenorConsumoActionPerformed);

        cmdPromedioCarga.setText("PROMEDIO CARGA");
        cmdPromedioCarga.addActionListener(this::cmdPromedioCargaActionPerformed);

        cmdBuscarCargaCamion.setText("BUSCAR CARGA CAMIONES");
        cmdBuscarCargaCamion.addActionListener(this::cmdBuscarCargaCamionActionPerformed);

        cmdListarCamiones.setText("LISTAR CAMIONES");
        cmdListarCamiones.addActionListener(this::cmdListarCamionesActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmdListarCamiones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmdCamionMenorConsumo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmdPromedioCarga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmdBuscarCargaCamion, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(cmdBuscarCargaCamion)
                .addGap(18, 18, 18)
                .addComponent(cmdCamionMenorConsumo)
                .addGap(21, 21, 21)
                .addComponent(cmdPromedioCarga)
                .addGap(18, 18, 18)
                .addComponent(cmdListarCamiones)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        cmdLIMPIAR.setText("LIMPIAR");
        cmdLIMPIAR.addActionListener(this::cmdLIMPIARActionPerformed);

        txtMOSTRAR.setColumns(20);
        txtMOSTRAR.setRows(5);
        txtMOSTRAR.setText("MOSTRAR");
        jScrollPane1.setViewportView(txtMOSTRAR);

        jButton1.setText("fecha ejem");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(cmdLIMPIAR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(38, 38, 38)
                .addComponent(jCalendarComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmdLIMPIAR)
                        .addComponent(jButton1))
                    .addComponent(jCalendarComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        setSize(new java.awt.Dimension(763, 482));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCamionMenorConsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCamionMenorConsumoActionPerformed
        // TODO add your handling code here:
    String cad=this.myPrincipal.getMyEmpresa().mostrarCamionMenorConsumo();
    this.txtMOSTRAR.setText(cad); 
        
        
    }//GEN-LAST:event_cmdCamionMenorConsumoActionPerformed

    private void cmdPromedioCargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdPromedioCargaActionPerformed
        // TODO add your handling code here:
        String cad = this.myPrincipal.getMyEmpresa().calcularPromedioCarga();
        this.txtMOSTRAR.setText(cad);
    }//GEN-LAST:event_cmdPromedioCargaActionPerformed

    private void cmdREGISTRARCAMIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdREGISTRARCAMIONActionPerformed
        // TODO add your handling code here:
        String placa = this.txtPLACA.getText();
        String carga = this.txtCARGA.getText();
        String consumo = this.txtCONSUMO.getText();
        if(placa.isEmpty()|carga.isEmpty()){
            Ventana.imp("hay datos vacios");
            return; 
        }
        String mensaje = this.myPrincipal.getMyEmpresa().registrarCamion(placa,Integer.parseInt(carga), Float.parseFloat(consumo));
        this.txtMOSTRAR.setText(mensaje);
    }//GEN-LAST:event_cmdREGISTRARCAMIONActionPerformed

    private void cmdLIMPIARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLIMPIARActionPerformed
        // TODO add your handling code here:
        this.txtPLACA.setText("");
        this.txtCARGA.setText("");
        this.txtCONSUMO.setText("");
        this.txtMOSTRAR.setText("");
    }//GEN-LAST:event_cmdLIMPIARActionPerformed

    private void cmdBuscarCargaCamionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBuscarCargaCamionActionPerformed
        // TODO add your handling code here:
      int carga=Ventana.leerInt("Digitar Carga: ");
      String cad=this.myPrincipal.getMyEmpresa().buscarCamionCarga(carga);
      this.txtMOSTRAR.setText(cad); 
    }//GEN-LAST:event_cmdBuscarCargaCamionActionPerformed

    private void cmdListarCamionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdListarCamionesActionPerformed
        // TODO add your handling code here:
         String cad=this.myPrincipal.getMyEmpresa().listarCamiones();
         this.txtMOSTRAR.setText(cad); 
    }//GEN-LAST:event_cmdListarCamionesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
        Date fecha= this.jCalendarComboBox1.getDate();
        int dia=fecha.getDate();
        int mes=fecha.getMonth()+1;
        int year=fecha.getYear()+1900;
        this.txtMOSTRAR.setText(dia+"/"+mes+"/"+year); 
    }//GEN-LAST:event_jButton1ActionPerformed
     
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBuscarCargaCamion;
    private javax.swing.JButton cmdCamionMenorConsumo;
    private javax.swing.JButton cmdLIMPIAR;
    private javax.swing.JButton cmdListarCamiones;
    private javax.swing.JButton cmdPromedioCarga;
    private javax.swing.JButton cmdREGISTRARCAMION;
    private javax.swing.JButton jButton1;
    private de.wannawork.jcalendar.JCalendarComboBox jCalendarComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCARGA;
    private javax.swing.JTextField txtCONSUMO;
    private javax.swing.JTextArea txtMOSTRAR;
    private javax.swing.JTextField txtPLACA;
    // End of variables declaration//GEN-END:variables
}
