/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Negocio.Empresa;

/**
 *
 * @author geral
 */
public class FormPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormPrincipal.class.getName());
    
    private Empresa myEmpresa;
    private FormRegistrarSalida myFormSalida;
    private FormRegistrarBus myFormBus;
    private FormRegistrarRuta myFormRuta;
    private FormCaja myFormCaja;
    private FormVenderTicket myFormVender;
    
    
 
 
    public FormPrincipal() {
        initComponents();
        myEmpresa =new Empresa();
        
    }

    public Empresa getMyEmpresa() {
        return myEmpresa;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        cmdCaja = new javax.swing.JButton();
        cmdRuta = new javax.swing.JButton();
        cmdBus = new javax.swing.JButton();
        cmdSalida = new javax.swing.JButton();
        cmdVenderPasaje = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmdCaja.setText("INICIAR CAJA");
        cmdCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCajaActionPerformed(evt);
            }
        });

        cmdRuta.setText("GESTIONAR RUTAS");
        cmdRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRutaActionPerformed(evt);
            }
        });

        cmdBus.setText("GESTIONAR BUSES");
        cmdBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBusActionPerformed(evt);
            }
        });

        cmdSalida.setText("GESTIONAR SALIDAS");
        cmdSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSalidaActionPerformed(evt);
            }
        });

        cmdVenderPasaje.setText("VENTA DE PASAJES");
        cmdVenderPasaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdVenderPasajeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(cmdCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(cmdVenderPasaje))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(cmdRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdBus, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdCaja)
                    .addComponent(cmdVenderPasaje))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdBus)
                    .addComponent(cmdSalida)
                    .addComponent(cmdRuta))
                .addGap(91, 91, 91))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCajaActionPerformed
        this.myFormCaja=new FormCaja(this);
        this.myFormCaja.setVisible(true);

    }//GEN-LAST:event_cmdCajaActionPerformed

    private void cmdRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRutaActionPerformed
        this.myFormRuta= new FormRegistrarRuta(this);
        this.myFormRuta.setVisible(true);
    }//GEN-LAST:event_cmdRutaActionPerformed

    private void cmdBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBusActionPerformed
          this.myFormBus=new FormRegistrarBus(this);
          this.myFormBus.setVisible(true);
    }//GEN-LAST:event_cmdBusActionPerformed

    private void cmdSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSalidaActionPerformed
       this.myFormSalida = new FormRegistrarSalida(this);
       this.myFormSalida.setVisible(true);
    }//GEN-LAST:event_cmdSalidaActionPerformed

    private void cmdVenderPasajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdVenderPasajeActionPerformed
        this.myFormVender= new FormVenderTicket(this);
        this.myFormVender.setVisible(true);
    }//GEN-LAST:event_cmdVenderPasajeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBus;
    private javax.swing.JButton cmdCaja;
    private javax.swing.JButton cmdRuta;
    private javax.swing.JButton cmdSalida;
    private javax.swing.JButton cmdVenderPasaje;
    private javax.swing.JColorChooser jColorChooser1;
    // End of variables declaration//GEN-END:variables
}
