/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author LENOVO LOQ
 */
public class FormCaja extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormCaja.class.getName());
    
    private FormPrincipal myFormPrinc;
    public FormCaja(FormPrincipal fp) {
        initComponents();
        this.myFormPrinc = fp;
        this.cargaSubtotal();
        this.cargaTotal();
        this.cargarCajaFinal();
        this.cargarTotalReembolso();
        this.cargarIngresoNeto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRembolso = new javax.swing.JLabel();
        lblTotalVendido = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        Jlabel22 = new javax.swing.JLabel();
        txtMensaje = new javax.swing.JScrollPane();
        txtTexto = new javax.swing.JTextArea();
        Jlabel23 = new javax.swing.JLabel();
        Jlabel24 = new javax.swing.JLabel();
        lblIngresoNeto = new javax.swing.JLabel();
        lblCajaFinal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblRembolso.setForeground(new java.awt.Color(255, 0, 51));
        lblRembolso.setText("---------");

        lblTotalVendido.setForeground(new java.awt.Color(0, 0, 204));
        lblTotalVendido.setText("---------");

        jLabel39.setText("Total vendido:");

        jLabel40.setText("REPORTE DIARIO - RUTAS COLOMBIA ");

        Jlabel22.setText("Total reembolsado:");

        txtTexto.setColumns(20);
        txtTexto.setRows(5);
        txtMensaje.setViewportView(txtTexto);

        Jlabel23.setText("Caja final: ");

        Jlabel24.setText("Ingreso neto:");

        lblIngresoNeto.setBackground(new java.awt.Color(0, 0, 0));
        lblIngresoNeto.setForeground(new java.awt.Color(51, 255, 51));
        lblIngresoNeto.setText("---------");

        lblCajaFinal.setText("---------");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotalVendido, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Jlabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblRembolso, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50)
                        .addComponent(Jlabel23)
                        .addGap(18, 18, 18)
                        .addComponent(lblCajaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(167, 167, 167)
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel40)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Jlabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblIngresoNeto, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(txtMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotalVendido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Jlabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRembolso, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Jlabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIngresoNeto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Jlabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCajaFinal))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
private void cargaSubtotal(){
    String me= this.myFormPrinc.getMyEmpresa().resumenCajaRuta();
    this.txtTexto.setText(me);

}

private void cargaTotal(){
String me=this.myFormPrinc.getMyEmpresa().totalCaja();
this.lblTotalVendido.setText(me);
}

private void cargarCajaFinal(){
String me="--+---";
me=this.myFormPrinc.getMyEmpresa().mostrarCajaFinal();
this.lblCajaFinal.setText(me);
}

private void cargarTotalReembolso(){
String me="";
me=this.myFormPrinc.getMyEmpresa().mostrarReembolso();
this.lblRembolso.setText(me);
}

private void cargarIngresoNeto(){
String me="";
me=this.myFormPrinc.getMyEmpresa().mostrarIngresoNeto();
this.lblIngresoNeto.setText(me);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jlabel22;
    private javax.swing.JLabel Jlabel23;
    private javax.swing.JLabel Jlabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel lblCajaFinal;
    private javax.swing.JLabel lblIngresoNeto;
    private javax.swing.JLabel lblRembolso;
    private javax.swing.JLabel lblTotalVendido;
    private javax.swing.JScrollPane txtMensaje;
    private javax.swing.JTextArea txtTexto;
    // End of variables declaration//GEN-END:variables
}
