/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;


import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;



public class FormRegistrarSalida extends javax.swing.JFrame {
    private FormPrincipal myFormPrinc;
    private GregorianCalendar fechaHora;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormRegistrarSalida.class.getName());
            
    public FormRegistrarSalida(FormPrincipal fp) {
        this.myFormPrinc=fp;
        initComponents();
        
        this.cargarIdeSalida();
        this.cargarRutas();
        SpinnerDateModel modeloHora =new SpinnerDateModel();
        this.spnHora.setModel(modeloHora);
        JSpinner.DateEditor editor =new JSpinner.DateEditor(spnHora,"HH:mm");
        
        this.spnHora.setEditor(editor);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbBus = new javax.swing.JComboBox<>();
        cmbRuta = new javax.swing.JComboBox<>();
        spnHora = new javax.swing.JSpinner();
        cmdRegistrarSalida = new javax.swing.JButton();
        jdtFecha = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmdListarSalida = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMensaje = new javax.swing.JTextArea();
        lblIdSalida = new javax.swing.JLabel();
        cmdCargarBuces = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("ID SALIDA:");

        jLabel2.setText("RUTA:");

        jLabel3.setText("BUS:");

        cmbBus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR" }));

        cmdRegistrarSalida.setText("REGISTRAR SALIDA");
        cmdRegistrarSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRegistrarSalidaActionPerformed(evt);
            }
        });

        jLabel4.setText("FECHA:");

        jLabel5.setText("HORA:");

        cmdListarSalida.setText("LISTAR SALIDAS");
        cmdListarSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdListarSalidaActionPerformed(evt);
            }
        });

        txtMensaje.setColumns(20);
        txtMensaje.setRows(5);
        jScrollPane1.setViewportView(txtMensaje);

        lblIdSalida.setText("------");

        cmdCargarBuces.setText("CARGAR BUCES");
        cmdCargarBuces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCargarBucesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cmbRuta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jdtFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                        .addComponent(lblIdSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(spnHora, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmdCargarBuces)
                                    .addComponent(cmbBus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(cmdListarSalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(cmdRegistrarSalida)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblIdSalida))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmdListarSalida)
                    .addComponent(cmbRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jdtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spnHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbBus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addComponent(cmdCargarBuces))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(cmdRegistrarSalida)
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdRegistrarSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRegistrarSalidaActionPerformed
        String id= this.lblIdSalida.getText();
        this.captarFechayHora();
        if (this.fechaHora == null) {
            this.txtMensaje.setText("SELECCIONE UNA FECHA Y HORA VÁLIDAS PARA CONTINUAR");
            return;
        }
        if (this.cmbRuta.getSelectedItem() == null || this.cmbBus.getSelectedItem() == null) {
            this.txtMensaje.setText("INGRESE TODOS LOS DATOS PARA PODER CONTINUAR");
            return;
        }
        String ruta= this.cmbRuta.getSelectedItem().toString();
        String codigoRuta=this.extraerCodigoRuta(ruta);
        String placa=this.cmbBus.getSelectedItem().toString();
        if(id.isEmpty()||ruta.isEmpty()||codigoRuta.isEmpty()||placa.isEmpty()){
            this.txtMensaje.setText("INGRESE TODOS LOS DATOS PARA PODER CONTINUAR");
        }else{
        
        String resultado = this.myFormPrinc.getMyEmpresa().registrarSalida(id, fechaHora, placa, codigoRuta);
        this.txtMensaje.setText(resultado);
        this.captarFechayHora();
        this.cargarBusces();
        this.cargarIdeSalida();}
   
    }//GEN-LAST:event_cmdRegistrarSalidaActionPerformed

    private void cmdListarSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdListarSalidaActionPerformed
        txtMensaje.setText(myFormPrinc.getMyEmpresa().listarSalida());
    }//GEN-LAST:event_cmdListarSalidaActionPerformed

    private void cmdCargarBucesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCargarBucesActionPerformed
        this.captarFechayHora();
        this.cargarBusces();
    }//GEN-LAST:event_cmdCargarBucesActionPerformed


    /**
     * @param args the command line arguments
     */

private void cargarIdeSalida(){
 String me=this.myFormPrinc.getMyEmpresa().generarIdSalida();
 this.lblIdSalida.setText(me);
}

private void cargarRutas(){
for(String s: this.myFormPrinc.getMyEmpresa().mostrarRutaComboBox()){
    this.cmbRuta.addItem(s);
}
}

private void cargarBusces(){
this.cmbBus.removeAllItems();
ArrayList<String> buces= new ArrayList();
buces= this.myFormPrinc.getMyEmpresa().busDisponibleComboBox(this.fechaHora);
for(String b: buces){
this.cmbBus.addItem(b);
}
}

//Este metodo se encarga de convertir los datos del spinner y jcalender en gregorianCalender
private void captarFechayHora(){
Date fecha= jdtFecha.getDate();
Date hora= (Date)spnHora.getValue();
    GregorianCalendar auxHora= new GregorianCalendar();
    auxHora.setTime(hora);
int hH = 0;
int mm = 0;
    GregorianCalendar fechaHora= new GregorianCalendar();
    fechaHora.setTime(fecha);
    
    hH= auxHora.get(GregorianCalendar.HOUR_OF_DAY);
    mm= auxHora.get(GregorianCalendar.MINUTE);
    
    fechaHora.set(GregorianCalendar.HOUR_OF_DAY,hH);
    fechaHora.set(GregorianCalendar.MINUTE,mm);
    this.fechaHora=fechaHora;
    
}

private String extraerCodigoRuta(String ruta){
String[] me =new String[2];
me=ruta.split(" ");

return me[0];
}
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbBus;
    private javax.swing.JComboBox<String> cmbRuta;
    private javax.swing.JToggleButton cmdCargarBuces;
    private javax.swing.JButton cmdListarSalida;
    private javax.swing.JButton cmdRegistrarSalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdtFecha;
    private javax.swing.JLabel lblIdSalida;
    private javax.swing.JSpinner spnHora;
    private javax.swing.JTextArea txtMensaje;
    // End of variables declaration//GEN-END:variables
}
