/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

/**
 *
 * @author USUARIO
 */
public class FormJugadores extends javax.swing.JFrame {

    /**
     * Creates new form FormJugadores
     */
    private FormPrincipal myP;
    
    public FormJugadores(FormPrincipal p, int panel) {
        initComponents();
        this.myP=p;
        this.deshabilitarPanel(panel);
    }

    private void deshabilitarPanel(int p){
        if(p==1){
            this.cmdRegistrarJ.setEnabled(true); 
            this.cmdMostrarTodosJ.setEnabled(false); 
            this.cmdPorPosicionJ.setEnabled(false); 
            this.cmdPorEstadoJ.setEnabled(false); 
            this.cmdBorrarMJ.setEnabled(false);
       } else {
            this.cmdRegistrarJ.setEnabled(false); 
            this.cmdMostrarTodosJ.setEnabled(true); 
            this.cmdPorPosicionJ.setEnabled(true); 
            this.cmdPorEstadoJ.setEnabled(true);  
            this.cmdBorrarMJ.setEnabled(true); 
      }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1RJ = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCedulaJ = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombreJ = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCorreoJ = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTelefonoJ = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtExperienciaJ = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCantPartidosJ = new javax.swing.JTextField();
        cmbPosicionJ = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtSueldoJ = new javax.swing.JTextField();
        cmdRegistrarJ = new javax.swing.JButton();
        jPanel2CJ = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMostrarJ = new javax.swing.JTextArea();
        cmdMostrarTodosJ = new javax.swing.JButton();
        cmdPorEstadoJ = new javax.swing.JButton();
        cmdPorPosicionJ = new javax.swing.JButton();
        cmdBorrarMJ = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1RJ.setBorder(javax.swing.BorderFactory.createTitledBorder("Registrar Jugadores"));

        jLabel1.setText("CEDULA:");

        txtCedulaJ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCedulaJMouseClicked(evt);
            }
        });

        jLabel2.setText("NOMBRE:");

        jLabel3.setText("CORREO:");

        jLabel4.setText("TELEFONO:");

        jLabel5.setText("POSICION QUE JUEGA:");

        jLabel6.setText("AÑOS EXPERIENCIA:");

        jLabel7.setText("CANTIDAD PARTIDOS:");

        cmbPosicionJ.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "portero", "lateral", "defensa", "delantero", "centrocampista", "centro delantero" }));

        jLabel8.setText("SUELDO:");

        cmdRegistrarJ.setText("REGISTRAR");
        cmdRegistrarJ.setEnabled(false);
        cmdRegistrarJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRegistrarJActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1RJLayout = new javax.swing.GroupLayout(jPanel1RJ);
        jPanel1RJ.setLayout(jPanel1RJLayout);
        jPanel1RJLayout.setHorizontalGroup(
            jPanel1RJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1RJLayout.createSequentialGroup()
                .addGroup(jPanel1RJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1RJLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1RJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1RJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1RJLayout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtCedulaJ, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1RJLayout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtNombreJ, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1RJLayout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtCorreoJ, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1RJLayout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtTelefonoJ, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1RJLayout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtExperienciaJ, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1RJLayout.createSequentialGroup()
                                    .addGroup(jPanel1RJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1RJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cmbPosicionJ, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtCantPartidosJ, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1RJLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtSueldoJ, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1RJLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(cmdRegistrarJ, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1RJLayout.setVerticalGroup(
            jPanel1RJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1RJLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1RJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCedulaJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1RJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombreJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1RJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCorreoJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1RJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTelefonoJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1RJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtExperienciaJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1RJLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1RJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cmbPosicionJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1RJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCantPartidosJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1RJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtSueldoJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cmdRegistrarJ)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel2CJ.setBorder(javax.swing.BorderFactory.createTitledBorder("Consultar Jugadores"));

        txtMostrarJ.setColumns(20);
        txtMostrarJ.setRows(5);
        jScrollPane1.setViewportView(txtMostrarJ);

        cmdMostrarTodosJ.setText("MOSTRAR TODOS");
        cmdMostrarTodosJ.setEnabled(false);
        cmdMostrarTodosJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMostrarTodosJActionPerformed(evt);
            }
        });

        cmdPorEstadoJ.setText("POR ESTADO");
        cmdPorEstadoJ.setEnabled(false);

        cmdPorPosicionJ.setText("POR POSICIÓN");
        cmdPorPosicionJ.setEnabled(false);

        cmdBorrarMJ.setText("BORRAR");
        cmdBorrarMJ.setEnabled(false);
        cmdBorrarMJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarMJActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2CJLayout = new javax.swing.GroupLayout(jPanel2CJ);
        jPanel2CJ.setLayout(jPanel2CJLayout);
        jPanel2CJLayout.setHorizontalGroup(
            jPanel2CJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2CJLayout.createSequentialGroup()
                .addGroup(jPanel2CJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2CJLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2CJLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cmdMostrarTodosJ)
                        .addGap(26, 26, 26)
                        .addComponent(cmdPorEstadoJ, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmdPorPosicionJ, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmdBorrarMJ)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2CJLayout.setVerticalGroup(
            jPanel2CJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2CJLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2CJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdMostrarTodosJ)
                    .addComponent(cmdPorEstadoJ)
                    .addComponent(cmdPorPosicionJ)
                    .addComponent(cmdBorrarMJ))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1RJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2CJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2CJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1RJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdRegistrarJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRegistrarJActionPerformed
        // TODO add your handling code here:
        String cedula=this.txtCedulaJ.getText();
        String nombre=this.txtNombreJ.getText();
        String correo=this.txtCorreoJ.getText();
        String telefono=this.txtTelefonoJ.getText();
        String posicion=this.cmbPosicionJ.getSelectedItem().toString();
        
        if(cedula.isEmpty()||nombre.isEmpty()||correo.isEmpty()||telefono.isEmpty()
              ||this.txtCantPartidosJ.getText().isEmpty()||this.txtSueldoJ.getText().isEmpty()||this.txtExperienciaJ.getText().isEmpty()){
            Ventana.imp("ESPACIOS VACIOS... DILIGENCIAR TODOS LOS CAMPOS", "SISTEMA..");
            return;
        }
        int cantPart= Integer.parseInt(this.txtCantPartidosJ.getText());
        int sueldo=Integer.parseInt(this.txtSueldoJ.getText());
        int exper=Integer.parseInt(this.txtExperienciaJ.getText());
        Ventana.imp(this.myP.getMyEmpresa().recepcionarHojasVidaJugador(cedula, nombre, correo, telefono, posicion, cantPart, sueldo,exper),"sistema");
        
    }//GEN-LAST:event_cmdRegistrarJActionPerformed

   private void limpiarControles(){
       this.txtCedulaJ.setText("");
       this.txtNombreJ.setText("");
       this.txtCorreoJ.setText("");
       this.txtTelefonoJ.setText("");
       this.txtExperienciaJ.setText("");
       this.txtSueldoJ.setText("");
       this.txtCantPartidosJ.setText("");
       
   }
    private void txtCedulaJMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCedulaJMouseClicked
        // TODO add your handling code here:
        this.limpiarControles();
    }//GEN-LAST:event_txtCedulaJMouseClicked

    private void cmdMostrarTodosJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMostrarTodosJActionPerformed
        // TODO add your handling code here:
        this.txtMostrarJ.setText(this.myP.getMyEmpresa().mostrarTodosJugadores());
        
    }//GEN-LAST:event_cmdMostrarTodosJActionPerformed

    private void cmdBorrarMJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarMJActionPerformed
        // TODO add your handling code here:
        this.txtMostrarJ.setText(""); 
    }//GEN-LAST:event_cmdBorrarMJActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbPosicionJ;
    private javax.swing.JButton cmdBorrarMJ;
    private javax.swing.JButton cmdMostrarTodosJ;
    private javax.swing.JButton cmdPorEstadoJ;
    private javax.swing.JButton cmdPorPosicionJ;
    private javax.swing.JButton cmdRegistrarJ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1RJ;
    private javax.swing.JPanel jPanel2CJ;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCantPartidosJ;
    private javax.swing.JTextField txtCedulaJ;
    private javax.swing.JTextField txtCorreoJ;
    private javax.swing.JTextField txtExperienciaJ;
    private javax.swing.JTextArea txtMostrarJ;
    private javax.swing.JTextField txtNombreJ;
    private javax.swing.JTextField txtSueldoJ;
    private javax.swing.JTextField txtTelefonoJ;
    // End of variables declaration//GEN-END:variables
}
