/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;
import Negocio.Empresa;

/**
 *
 * @author USUARIO
 */
public class FormPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormPrincipal
     */
    
    private Empresa myEmpresa;
    
    
    public FormPrincipal() {
        initComponents();
        this.myEmpresa=new Empresa();
    }

    public Empresa getMyEmpresa() {
        return myEmpresa;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jmJugador = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmitRegistrarJ = new javax.swing.JMenuItem();
        jmitConsultarJ = new javax.swing.JMenuItem();
        jmTecnico = new javax.swing.JMenu();
        jmitRegistrarT = new javax.swing.JMenuItem();
        jmiConsultarT = new javax.swing.JMenuItem();
        jmEquipo = new javax.swing.JMenu();
        jmiRegistrarE = new javax.swing.JMenuItem();
        jmiConsultarE = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Jugadores");

        jmitRegistrarJ.setText("Registrar");
        jmitRegistrarJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitRegistrarJActionPerformed(evt);
            }
        });
        jMenu1.add(jmitRegistrarJ);

        jmitConsultarJ.setText("Consultar");
        jmitConsultarJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitConsultarJActionPerformed(evt);
            }
        });
        jMenu1.add(jmitConsultarJ);

        jmJugador.add(jMenu1);

        jmTecnico.setText("Tecnicos");

        jmitRegistrarT.setText("Registrar");
        jmTecnico.add(jmitRegistrarT);

        jmiConsultarT.setText("Consultar");
        jmTecnico.add(jmiConsultarT);

        jmJugador.add(jmTecnico);

        jmEquipo.setText("Equipos");
        jmEquipo.setEnabled(false);

        jmiRegistrarE.setText("Registrar");
        jmEquipo.add(jmiRegistrarE);

        jmiConsultarE.setText("Consultar");
        jmEquipo.add(jmiConsultarE);

        jmJugador.add(jmEquipo);

        setJMenuBar(jmJugador);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 811, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 432, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmitConsultarJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitConsultarJActionPerformed
        // TODO add your handling code here:
        if(this.myEmpresa.retornarCantidadJugadores()==0){
            Ventana.imp("NO HAY JUGADORES PARA MOSTRAR", "SISTEMA..");
            return;
        }
            FormJugadores formJ=new FormJugadores(this,2);
            formJ.setVisible(true);
             
         
       
    }//GEN-LAST:event_jmitConsultarJActionPerformed

    private void jmitRegistrarJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitRegistrarJActionPerformed
        // TODO add your handling code here:
        FormJugadores formJ=new FormJugadores(this,1);
        formJ.setVisible(true); 
        
    }//GEN-LAST:event_jmitRegistrarJActionPerformed

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jmEquipo;
    private javax.swing.JMenuBar jmJugador;
    private javax.swing.JMenu jmTecnico;
    private javax.swing.JMenuItem jmiConsultarE;
    private javax.swing.JMenuItem jmiConsultarT;
    private javax.swing.JMenuItem jmiRegistrarE;
    private javax.swing.JMenuItem jmitConsultarJ;
    private javax.swing.JMenuItem jmitRegistrarJ;
    private javax.swing.JMenuItem jmitRegistrarT;
    // End of variables declaration//GEN-END:variables
}
